

services:
  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000

    ports:
      - "8000:8000"

    environment:
      DB_HOST: pg-35318557-cuilahore-63ed.j.aivencloud.com
      DB_PORT: 19969
      DB_NAME: defaultdb
      DB_USER: avnadmin
      DB_PASSWORD: AVNS_OQ0K1gICnzak5iV_ukC

    

    networks:
      - app-network


  

  # ğŸ˜ PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_OQ0K1gICnzak5iV_ukC
      POSTGRES_DB: defaultdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

# ğŸ”— Internal Docker network (auto handles container communication)
networks:
  app-network:
    driver: bridge

# ğŸ’¾ Persistent volume for database
volumes:
  postgres_data:
