apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_HOST: "pg-35318557-cuilahore-63ed.j.aivencloud.com"
  DB_PORT: "19969"
  DB_USER: "avnadmin"
  DB_PASSWORD: "AVNS_OQ0K1gICnzak5iV_ukC"
  DB_NAME: "defaultdb"
