apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsfinal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsfinal-backend
  template:
    metadata:
      labels:
        app: devopsfinal-backend
    spec:
      containers:
        - name: devopsfinal-backend
          image: musa56/devopsfinal-backend:latest
          ports:
            - containerPort: 8000
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          envFrom:
            - secretRef:
                name: postgres-secret
