apiVersion: v1
kind: Service
metadata:
  name: devopsfinal-backend
spec:
  selector:
    app: devopsfinal-backend
  ports:
    - port: 80         # Service port
      targetPort: 8000 # Pod container port
      nodePort: 30080   # Fixed port on host
  type: NodePort       # Use NodePort for Docker Desktop
