apiVersion: v1
kind: Service
metadata:
  name: backend-app
  namespace: demo-app
spec:
  selector:
    app: backend-app
  ports:
    - port: 80         # Service port
      targetPort: 8000 # Pod container port
      nodePort: 30080   # Fixed port on host
  type: NodePort       # Use NodePort for Docker Desktop
